project:
  type: blog
  output-dir: docs
  resources:
    - CNAME


website:
  title: "Alles rund um Python, Daten und Künstliche Intelligenz"
  navbar:
    right:
      - about.qmd
      - icon: heart
        href: https://aneifer.de
      - icon: github
        href: https://github.com/Aneifer
      - icon: linkedin
        href: https://www.linkedin.com/in/anna-neifer/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.cssheart



